# Workflow to build and deploy to your GitHub Pages repo.

# Edit your project details here.
# Remember to add API_TOKEN_GITHUB in repo Settings > Secrets as well!
env:
  githubEmail: chrislhamelin@gmail.com
  deployToRepo: enverse.github.io

name: Github Pages Astro CI

on:
  # Triggers the workflow on push and pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [15]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      # Create env file with variables
      - name: Create environement variables
        run: |
          touch .env
          echo PUBLIC_CONTENTFUL_API=${{ secrets.PUBLIC_CONTENTFUL_API }} >> .env
          echo '\n' >> .env
          echo PUBLIC_CONTENTFUL_SPACE=${{ secrets.PUBLIC_CONTENTFUL_SPACE }} >> .env
          echo '\n' >> .env
          echo PUBLIC_FORMSPREE_KEY_CONTACT=${{ secrets.PUBLIC_FORMSPREE_KEY_CONTACT }} >> .env
          echo '\n' >> .env
          echo PUBLIC_FORMSPREE_FUNNEL_KEY=${{ secrets.PUBLIC_FORMSPREE_FUNNEL_KEY }} >> .env

      # Build the project and add .nojekyll file to supress default behaviour
      - name: Build
        run: |
          pnpm build --experimental-integrations
          touch ./dist/.nojekyll
          echo https://www.enverselabs.com > ./dist/CNAME

      # Push to your pages repo
      - name: Push to pages repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-github-username: enverse
          destination-repository-name: ${{ env.deployToRepo }}
          user-email: ${{ env.githubEmail }}
          commit-message: Deploy ORIGIN_COMMIT
          target-branch: gh-pages
